version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_salud_laboral
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123_duoc
      POSTGRES_DB: db_salud_laboral
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: